blog/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('blog/', views.BlogTemplateView.as_view(), name='blog'),

    path('add_blog/', views.BlogAddTemplateView.as_view(), name='add_blog'),

    path('edit_blog/<int:pk>/', views.BlogEditTemplateView.as_view(), name='edit_blog'),

    path('blog_detail/<int:pk>/', views.BlogDetailTemplateView.as_view(), name='blog_detail')

]

drf_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView, )
from rest_framework.schemas import get_schema_view  # hamro schema or endpoints haru dekhaucha
from rest_framework.documentation import include_docs_urls  # hamro endpoint dekhaune gui ho

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # Simple JWT authentication url ho yo 
    # url for getting token
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # url for refreshing token
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    # URL for Django Provided Default Admin Panel
    path('admin/', admin.site.urls),

    # Using namespace in the include() allows you to include the same app more than once, with a different namespace. Here the blog app is included many times with different namespaces.
    path('', include('blog.urls')),

    # URL for Blog_API Application (api endpoints to entry point ho yo)
    path('api/', include('blog_api.urls')),

    # users app ko urls.py ma hit hanne url ho yo
    path('api/user/', include('users.urls')),

    # DRF le provide gareko login & logount garne authentication url ho
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # url for schema generation
    path('schema/', get_schema_view(
        title="BlogAPI",
        description="API for the Blog Post",
        version="1.0.0"
    ), name='openapi-schema'),

    # url for gui document generation
    path('docs/', include_docs_urls(title='BlogAPI')),

    # Home Url
    path('', include('home.urls')),

    # login_signup urls
    path('', include('login_signup.urls')),

]

# yesari settings.py ma mention vako media directory chinauna ko lagi urlpattern lekhnu parcha
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_signup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.LoginTemplateView.as_view(), name='login'),
    path('signup/', views.SingnupTemplateView.as_view(), name='signup'),

]

users/urls.py
from django.urls import path
from .views import CustomUserCreate, BlacklistTokenUpdateView

app_name = 'users'

urlpatterns = [

    path('create/', CustomUserCreate.as_view(), name="create_user"),
    
    path('logout/blacklist/', BlacklistTokenUpdateView.as_view(), name='blacklist')

]

login_signup/models.py
from django.db import models

# Create your models here.

login_signup/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class LoginTemplateView(TemplateView):
    template_name = 'login_signup/login.html'


class SingnupTemplateView(TemplateView):
    template_name = 'login_signup/signup.html'

login_signup/templates/login_signup/login.html
{% extends 'login_signup/login_signup_base.html' %}

{% load static %}

{% block body %}

    <script src="{% static 'assets/js/token/token.js' %}"></script>

    <main class="login-body" data-vide-bg="{% static 'assets/img/login-bg.mp4' %}">
        <!-- Login Admin -->
        <form class="form-default" id="form_wrapper">

            <div class="login-form">
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="{% url 'home' %}"><img src="{% static 'assets/img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Login Here</h2>
                <div class="form-input">
                    <label for="name">Email</label>
                    <input type="email" name="email" placeholder="Email" id="email" required>

                </div>
                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" placeholder="Password" id="password" required>
                </div>
                <div class="form-input pt-30">
                    <input type="submit" name="submit" value="login" id="login_btn">
                </div>


                <!-- Create new user -->
                <a href="{% url 'signup' %}" style="margin-left: 38%; margin-top: 5%;" class="registration">Registration</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>



    <script type="text/javascript">


        $(document).ready(function () {


            var csrftoken = getToken('csrftoken');			/* csrftoken yesari generate garera variable ma holda garayera rakheko cha,,, getToken() vanni csrf token generate garni auta django le diyeko method ho.. yo django ko documentation ma diyeko cha ... tesailai copy paste gareko*/
            {#console.log('token:' + csrftoken)#}


            var form = document.getElementById('form_wrapper')		/* from-wrapper vanni element lai get gareko */

            /* hamro form submission garne kaam javascript le handle gari rako cha.. not by the django */
            form.addEventListener('submit', function (e)		                 /* form ko submit ma kasaile click gareko cha vani, yo talako definition part run hune*/ {
                e.preventDefault()                                           /* yo code le chai form automatic submit huna prevent garcha ... i.e prevent form from submitting on it's own ... generally form ko submit ma click garyo vani form submit hune kaam hunthyo,,, but tyo kam hamile javscript batw handle garna lagi rako chau */

                var email = document.getElementById('email').value
                var password = document.getElementById('password').value


                var url = "{% url 'token_obtain_pair' %}"			                                /* fetch API call garne wala url lai yesari js variable ma hold garera rakheko*/

                /* Fetch API Call to the url */
                fetch(url, {
                    method: 'POST',				                                            /* yo url ma hit hanne method vaneko chai POST method ho vanna khojeko*/
                    headers: {
                        Authorization: localStorage.getItem('access_token')
                            ? 'JWT ' + localStorage.getItem('access_token')
                            : null,

                        'Content-type': 'application/json',
                        'X-CSRFToken': csrftoken,			                                                 /* yo form batw csrf token pani pathaucha ,,,, csrftoken chai mathi top tira generate gareko cha... getToken() vanni function le generate gareko cha */
                    },
                    body: JSON.stringify({
                        'email': email,
                        'password': password,
                    })			                                                                            /* yesarri body ma json object vitra key value pair(i.e 'title':title) pani pathako cha*/

                }).then((resp) => resp.json())
                    .then(function (res)		                                                        /* django ko taskCreate() vanni view le response pathaye pachi yo function call huncha*/ {

                        localStorage.setItem('access_token', res.access);
                        localStorage.setItem('refresh_token', res.refresh);


                        document.getElementById('form_wrapper').reset()			                            /* JS ko  .reset() method will just clear out our form ma haleko display vai rakheko data */
                        {#window.location.replace("{% url 'blog' %}");#}

                        setAuthorization()
                    })

            })

            function setAuthorization()
            {

                var urls = "{% url 'list_post' %}"			                                /* fetch API call garne wala url lai yesari js variable ma hold garera rakheko*/

                /* Fetch API Call to the url */
                fetch(urls, {
                    method: 'GET',				                                            /* yo url ma hit hanne method vaneko chai POST method ho vanna khojeko*/
                    headers: {
                        Authorization: localStorage.getItem('access_token')
                            ? 'JWT ' + localStorage.getItem('access_token')
                            : null,


                        'Accept': 'application/json',
                        'X-CSRFToken': csrftoken,			                                                 /* yo form batw csrf token pani pathaucha ,,,, csrftoken chai mathi top tira generate gareko cha... getToken() vanni function le generate gareko cha */
                    },
                })
                    .then(function (response)		                                                        /* django ko taskCreate() vanni view le response pathaye pachi yo function call huncha*/ {

                        if (parseInt(response.status) == 200) {
                            if (localStorage.getItem('access_token') == 'undefined') {

                                window.location.replace("{% url 'login' %}")
                            } else {
                                window.location.replace("{% url 'blog' %}")

                            }
                        } else {
                            window.location.replace("{% url 'login' %}");

                        }
                    })


            }
        })
    </script>


{% endblock %}

login_signup/templates/login_signup/login_signup_base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> App landing</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="manifest" href="site.webmanifest">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico'%}">

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/progressbar_barfiller.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animated-headline.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">


    <!-- Jquery CDN Link -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>


</head>
<body>
<!-- ? Preloader Start -->
<div id="preloader-active">
    <div class="preloader d-flex align-items-center justify-content-center">
        <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
                <img src="{% static 'assets/img/logo/loder.png' %}" alt="">
            </div>
        </div>
    </div>
</div>
<!-- Preloader Start-->

{% block body %}
{% endblock %}





<script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script src="{% static 'assets/js/popper.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

<!-- Video bg -->
<script src="{% static 'assets/js/jquery.vide.js' %}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'assets/js/slick.min.js' %}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'assets/js/wow.min.js' %}"></script>
<script src="{% static 'assets/js/animated.headline.js' %}"></script>
<script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

<!-- Date Picker -->
<script src="{% static 'assets/js/gijgo.min.js' %}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
<!-- Progress -->
<script src="{% static 'assets/js/jquery.barfiller.js' %}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'assets/js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'assets/js/waypoints.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'assets/js/hover-direction-snake.min.js' %}"></script>

<!-- contact js -->
<script src="{% static 'assets/js/contact.js' %}"></script>
<script src="{% static 'assets/js/jquery.form.js' %}"></script>
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
<script src="{% static 'assets/js/mail-script.js' %}"></script>
<script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'assets/js/plugins.js' %}"></script>
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

login_signup/templates/login_signup/signup.html
{% extends 'login_signup/login_signup_base.html' %}
{% load static %}


{% block body %}

    <script src="{% static 'assets/js/token/token.js' %}"></script>

    <!-- Register -->
    <main class="login-body" data-vide-bg="{% static 'assets/img/login-bg.mp4' %}">
        <!-- Login Admin -->
        <form class="form-default" id="form_wrapper">

            <div class="login-form">
                <!-- logo-login -->
                <div class="logo-login">
                    <a href="{% url 'home' %}"><img src="{% static 'assets/img/logo/loder.png' %}" alt=""></a>
                </div>
                <h2>Registration Here</h2>

                <div class="form-input">
                    <label for="name">Username</label>
                    <input type="text" name="user_name" id="user_name" required>
                </div>

                <div class="form-input">
                    <label for="name">Email Address</label>
                    <input type="email" name="email" id="email" required>
                </div>

                <div class="form-input">
                    <label for="name">Password</label>
                    <input type="password" name="password" id="password" required>
                </div>

                <div class="form-input">
                    <label for="name">Confirm Password</label>
                    <input type="password" name="confirm_password" id="confirm_password" required>
                </div>

                <div class="form-input pt-30">
                    <input type="submit" id="submit" name="submit" value="Registration">
                </div>
                <!-- Forget Password -->
                <a href="{% url 'login' %}" style="margin-left: 43%;" class="registration">login</a>
            </div>
        </form>
        <!-- /end login form -->
    </main>



    <script type="text/javascript">

        var csrftoken = getToken('csrftoken');			/* csrftoken yesari generate garera variable ma holda garayera rakheko cha,,, getToken() vanni csrf token generate garni auta django le diyeko method ho.. yo django ko documentation ma diyeko cha ... tesailai copy paste gareko*/
        console.log('token:' + csrftoken)


        var form = document.getElementById('form_wrapper')		/* from-wrapper vanni element lai get gareko */

        /* hamro form submission garne kaam javascript le handle gari rako cha.. not by the django */
        form.addEventListener('submit', function (e)		                 /* form ko submit ma kasaile click gareko cha vani, yo talako definition part run hune*/ {
            e.preventDefault()                                           /* yo code le chai form automatic submit huna prevent garcha ... i.e prevent form from submitting on it's own ... generally form ko submit ma click garyo vani form submit hune kaam hunthyo,,, but tyo kam hamile javscript batw handle garna lagi rako chau */

            var user_name = document.getElementById('user_name').value		/* user_name vanni element lai get gareko */
            var email = document.getElementById('email').value
            var password = document.getElementById('password').value
            var confirm_password = document.getElementById('confirm_password').value

            if (password.trim() === '' || confirm_password.trim() === '' || password != confirm_password)
            {
                alert('password error')
            }
            else
            {
                var url = "{% url 'users:create_user' %}"			 //yaha 'users:create_user' gareko cha becz users app ko urls.py ma app_name = 'users' diyeko cha ...yesari app name diyo vani yesari ---> users:create_user dina parcha.

                /* Fetch API Call to the url */
                fetch(url, {
                    method: 'POST',				/* yo url ma hit hanne method vaneko chai POST method ho vanna khojeko*/
                    headers: {
                        'Content-type': 'application/json',
                        {#'Content-type': 'multipart/form-data',#}
                        'X-CSRFToken': csrftoken,			/* yo form batw csrf token pani pathaucha ,,,, csrftoken chai mathi top tira generate gareko cha... getToken() vanni function le generate gareko cha */
                    },
                    body: JSON.stringify({
                        'user_name': user_name,
                        'email': email,
                        'password': password,
                        'confirm_password': confirm_password
                     })			/* yesarri body ma json object vitra key value pair(i.e 'title':title) pani pathako cha*/

                   // body: new FormData(form_wrapper)
                })
                    .then(function (response)		/* django ko taskCreate() vanni view le response pathaye pachi yo function call huncha*/
                    {

                        document.getElementById('form_wrapper').reset()			/* JS ko  .reset() method will just clear out our form ma haleko display vai rakheko data */
                        window.location.replace("{% url 'login' %}");
                    })
            }
        })

    </script>
{% endblock %}